============================= test session starts ==============================
platform linux -- Python 3.10.2, pytest-7.4.1, pluggy-1.3.0
django: settings: settings.production (from env)
rootdir: /code
configfile: pyproject.toml
plugins: django-4.5.2, dotenv-0.5.2, cov-4.1.0
collected 7 items

autenticacion/tests.py ...F..                                            [ 85%]
test/test_prueba_pytest.py .                                             [100%]

=================================== FAILURES ===================================
___________________ AutenticacionTestCase.test_login_empresa ___________________

self = <autenticacion.tests.AutenticacionTestCase testMethod=test_login_empresa>

    def test_login_empresa(self):
        "Se testea que el login de una empresa sea correcto."
    
        client = self.client
    
        json_login_emp = {
            "email": self.usuarios["empresa"]["email"],
            "password": self.usuarios["empresa"]["password"],
        }
        response = client.post("/auth/login/", json_login_emp, format="json")
    
        assert response.status_code == status.HTTP_200_OK
        assert response.data["tipo_usuario"] == "empresa"
>       assert response.data["token"] is None
E       AssertionError: assert '5032f2ad76b2c592c3b19326e28057b26927a934271a9ce38f22be3fe09cec20' is None

autenticacion/tests.py:71: AssertionError
=========================== short test summary info ============================
FAILED autenticacion/tests.py::AutenticacionTestCase::test_login_empresa - As...
========================= 1 failed, 6 passed in 2.16s ==========================
